### ISSUE TITLE
Support latest singyeong features

### ISSUE THREAD

**Issue by queer** [PendragonLore/shinkei#3]
Implementation details are, as always, [available in the protocol documentation](https://github.com/queer/singyeong/blob/master/PROTOCOL.md).

- Tags are no longer a thing.
- Message queuing has been added.
- An official DSN format is included at the top of the protocol docs.

**Comment by LoryCS** [comment]
Hi! Sorry for the extremely late reply, but I won't be maintaining this library anymore. Feel free to remove it from the README.
